### ISSUE TITLE
More details about the 'Nesterov' reference ? 

### ISSUE THREAD

**Issue by lrnv** [PavelTrutman/SDP#4]
Hi, 

All over your code, you cite 'Nesterov', with pages numbers. Could you provide the full reference to this book ? I have troubles matching the pages numbers, since there might have been a re-edition, so if you provide the full reference you used it would be great 👍 

Nice code btw.

**Comment by PavelTrutman** [comment]
Hi,
the citation 'Nesterov' refers to
Yurii Nesterov. _Introductory lectures on convex optimization : A basic course._ Springer, 2004.

You may be also interested in my diploma thesis text, which describes the package Polyopt. It is available at http://people.ciirc.cvut.cz/~trutmpav/paper/master-thesis.pdf.
Pavel Trutman. _Semidefinite Programming for Geometric Problems in Computer Vision._ CTU in Prague, 2018.

If you still have any questition do not hesitate to ask.

**Comment by lrnv** [comment]
Thanks for the proper ref, I'll come back to you if I have more questions.

Nice code btw.

Le lun. 24 août 2020 à 18:35, Pavel Trutman <notifications@github.com> a
écrit :
